name: spell check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  fix-spelling:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Check and Fix Spelling
        uses: crate-ci/typos@v1.50.1
        continue-on-error: true 
        with:
          write_changes: true

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_user_name: typobot
          commit_user_email: typobot@project516.dev
          commit_message: "fix typos"
          branch: ${{ github.head_ref || github.ref_name }}
